env:
  - CGO_ENABLED=0
  - GO111MODULE=on

before:
  hooks:
    - go mod download

builds:
  - id: seqls
    main: ./cmd/seqls/
    binary: seqls
    ldflags: -s -w -X main.Version={{.Version}}
    goos:
      - windows
      - darwin
      - linux
    ignore:
      - goos: darwin
        goarch: "386"

  - id: seqinfo
    main: ./cmd/seqinfo/
    binary: seqinfo
    ldflags: -s -w -X main.Version={{.Version}}
    goos:
      - windows
      - darwin
      - linux
    ignore:
      - goos: darwin
        goarch: "386"


archives:
  - id: default
    wrap_in_directory: true
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}64-bit
      {{- else if eq .Arch "386" }}32-bit
      {{- else if eq .Arch "darwin" }}osx
      {{- else }}{{ .Arch }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
      - CHANGES
      - README.md

release:
  github:
    owner: justinfx
    name: gofileseq
  draft: true
  # You can change the name of the GitHub release.
  # This is parsed with the Go template engine and the following variables
  # are available:
  # - ProjectName
  # - Tag
  # - Version (Git tag without `v` prefix)
  # Default is ``
  name_template: "v{{.Version}} Release"

changelog:
  filters:
    # commit messages matching the regexp listed here will be removed from
    # the changelog
    # Default is empty
    exclude:
      - '^docs:'
      - typo
      - goreleaser
      - gitignore
      - '[tT]ravis'
      - '^ci:'
      - '^merge:'
      
